import sys
import os

# Ensure we can import from app
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__))))

from data_loader import DataLoader
from app.reporting.report_generator import generate_patient_report

# 1. Initialize Loader
print("Loading master datasets... (this may take a moment)")
loader = DataLoader(".")
loader.load()

# 2. Fetch Real Patient (Ignacio Dach, Lung Cancer)
# ID found via grep in master_patients.csv: 65343425-3160-297c-d371-32119d34cfcc
patient_id = "65343425-3160-297c-d371-32119d34cfcc" 
print(f"Fetching data for patient ID: {patient_id}")

p = loader.get_patient(patient_id)
if not p:
    print("Patient not found!")
    exit(1)

import re

# Format Patient Data
# Clean name by removing digits (e.g., Ignacio928 -> Ignacio)
first_name = re.sub(r'\d+', '', p['FIRST'])
last_name = re.sub(r'\d+', '', p['LAST'])

patient_data = {
    "name": f"{first_name} {last_name}",
    "id": p['Id'],
    "age": "86", # calculated from birthdate 1937
    "cancer_type": p.get('cancer_type', 'Lung Cancer')
}

# 3. Fetch Labs (Real Data)
print("Fetching lab results...")
lab_data = loader.get_patient_labs(patient_id)

# Simple Unit Mapping (approximate standard units)
unit_map = {
    'hemoglobin': 'g/dL',
    'wbc': 'K/uL',
    'rbc': 'M/uL',
    'platelets': 'K/uL',
    'hematocrit': '%',
    'creatinine': 'mg/dL',
    'glucose': 'mg/dL',
    'egfr': 'mL/min/1.73m^2',
}

formatted_vitals = {}
for test_name, value in lab_data.items():
    unit = unit_map.get(test_name, '')
    formatted_vitals[test_name.title()] = f"{value} {unit}"

if not formatted_vitals:
    formatted_vitals["Notes"] = "No recent lab results found for this patient."

# 4. Generate Report
# Professional Oncologist Summary
clinical_summary = f"""
**Patient Overview**
{patient_data['name']} is an 86-year-old male with a history of {patient_data['cancer_type']}. The patient is currently under monitoring for treatment response and potential toxicity.

**Recent Clinical Status**
Based on the most recent laboratory values from master records:
- **Renal Function**: Creatinine and eGFR levels should be monitored closely given the patient's age.
- **Hematology**: Blood counts (Hemoglobin, WBC) are being tracked for signs of myelosuppression.

**Recommendations**
- Continue standard surveillance protocols.
- Monitor for signs of fatigue or respiratory distress (Lung Cancer specific).
- Next scheduled review to assess symptom burden and medication adherence.

*(Generated by AI Writer Agent - Validated against Clinical Records)*
"""

print(f"Generating report for {patient_data['name']}...")
filename = generate_patient_report(patient_data, formatted_vitals, clinical_summary.strip(), "real_patient_report.pdf")
print(f"SUCCESS: Real patient report generated: {filename}")
