from fpdf import FPDF
import datetime

class PatientReportPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Weekly Patient History Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def add_patient_details(self, patient_data):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, f"Patient: {patient_data.get('name', 'Unknown')}", 0, 1)
        self.set_font('Arial', '', 10)
        self.cell(0, 6, f"ID: {patient_data.get('id', 'N/A')}", 0, 1)
        self.cell(0, 6, f"Age: {patient_data.get('age', 'N/A')}", 0, 1)
        self.cell(0, 6, f"Cancer Type: {patient_data.get('cancer_type', 'N/A')}", 0, 1)
        self.cell(0, 6, f"Report Date: {datetime.date.today()}", 0, 1)
        self.ln(5)

    def add_section(self, title, content):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, title, 0, 1, 'L', 1)
        self.ln(2)
        
        # Markdown Parsing (Basic: Bold ** and Bullets -)
        self.set_font('Arial', '', 10)
        lines = content.split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                self.ln(2) # Smaller gap for empty lines
                continue
            
            # Bullet points
            is_bullet = False
            if line.startswith('- '):
                is_bullet = True
                line = line[2:] # Remove bullet
                current_x = self.get_x()
                self.set_x(current_x + 5) # Indent
                self.cell(5, 5, chr(149), 0, 0) # Bullet character
            
            # Bold parsing (**text**)
            parts = line.split('**')
            for i, part in enumerate(parts):
                if i % 2 == 1: # Odd indices are inside ** ** -> BOLD
                    self.set_font('Arial', 'B', 10)
                    self.write(5, part)
                else: # Even indices are normal -> REGULAR
                    self.set_font('Arial', '', 10)
                    self.write(5, part)
            
            self.ln(5)
            # Reset X if it was a bullet
            if is_bullet:
                self.set_x(self.l_margin)
        self.ln(5)

    def add_vitals_clean(self, vitals):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, "Recent Vitals (Last 7 Days Arg)", 0, 1, 'L', 1)
        self.ln(2)
        self.set_font('Arial', '', 10)
        
        # Simple tabular display
        self.set_font('Courier', '', 9)
        for key, value in vitals.items():
            self.cell(50, 5, f"{key}:", 0, 0)
            self.cell(0, 5, f"{value}", 0, 1)
        self.ln(5)

def sanitize_text(text):
    if text is None: return ""
    return str(text).encode('latin-1', 'replace').decode('latin-1')

def generate_patient_report(patient_data, vitals, clinical_summary, filename="patient_report.pdf"):
    pdf = PatientReportPDF()
    pdf.add_page()
    
    # 1. Header Details
    pdf.add_patient_details(patient_data)
    
    # 2. Vitals / Metrics
    pdf.add_vitals_clean(vitals)
    
    # 3. Clinical Summary (Generated by Writer Agent)
    # The summary is expected to be a structured text block
    pdf.add_section("Clinical Summary (Writer Agent Output)", sanitize_text(clinical_summary))
    
    pdf.output(filename)
    return filename
